v = input('Digite algo: ')

print(type(v))
print(v.isalpha())
print(v.isnumeric())
print(v.isalnum())
print(v.isascii())
print(v.isdecimal())
print(v.isdigit())
print(v.isidentifier())
print(v.islower())
print(v.isupper())
print(v.isprintable())
print(v.isspace())
print(v.istitle())
